version: '3.3'

services:

  # mariadb service
  database:
    image: mariadb:${MARIADB_VERSION:-10.5.8}
    container_name: database
    volumes: 
      - ${DATABASE_DATA_DIR:-./data}:/var/lib/mysql
      - ${DATABASE_IMPORT_DIR:-./data/import}:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-password}
      MYSQL_DATABASE: ${DATABASE_NAME:-wordpress}
      MYSQL_USER: ${DATABASE_USER:-wordpress}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-password}
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - wordpress-network

  # wordpress service
  wordpress:
    depends_on: 
      - database
    image: wordpress:${WORDPRESS_VERSION:-php7.4-fpm-alpine}
    container_name: wordpress
    restart: always
    user: "root:root"
    environment: 
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: ${DATABASE_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD:-password}
      WORDPRESS_DB_NAME: ${DATABASE_NAME:-wordpress}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_PREFIX:-wp_}
      WORDPRESS_DEBUG: ${WP_DEBUG:-0}
      WORDPRESS_CONFIG_EXTRA: |
        /* Site URL */
        define( 'WP_HOME', '${WORDPRESS_HOMEURL:-http://localhost:8080}' );
        define( 'WP_SITEURL', '${WORDPRESS_SITEURL:-http://localhost:8080}' );
    volumes:
      - ${PHP_CONFIG:-./config/php.ini}:/usr/local/etc/php/conf.d/custom.ini
      - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html
      - ${WORDPRESS_THEMES_DIR:-./themes}:/var/www/html/wp-content/themes
      - ${WORDPRESS_PLUGINS_DIR:-./plugins}:/var/www/html/wp-content/plugins
      - ${WORDPRESS_UPLOADS_DIR:-./uploads}:/var/www/html/wp-content/uploads
    networks:
      - wordpress-network

  # caddy webserver service
  caddy:
    image: caddy:${CADDY_VERSION:-2.3.0-alpine}
    container_name: webserver
    environment: 
      CADDY_DOMAIN: ${CADDY_DOMAIN:-http://localhost:8080}
    ports:
      - ${CADDY_HTTP_PORT:-8080}:80
      - ${CADDY_HTTPS_PORT:-8443}:443
    volumes:
      - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html
      - ${CADDY_DATA_DIR:-./caddy/data}:/data
      - ${CADDY_CONFIG_DIR:-./caddy/config}:/config
      - ${CADDYFILE-./config/Caddyfile}:/etc/caddy/Caddyfile
    networks:
     - wordpress-network

networks:
  wordpress-network:
    driver: bridge